version: '3.9'

services:
  rabbitmq:
    image: rabbitmq:4
    container_name: rabbitmq
    ports:
      - "5672:5672" # Default RabbitMQ AMQP port
      - "15672:15672" # RabbitMQ Management UI port
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  build_run_crawler:
    build:
      context: ..
      dockerfile: docker/build_run_crawler.yml
    container_name: build_run_crawler
    depends_on:
      rabbitmq:
        condition: service_healthy
